development:
  adapter: postgresql
  database: mind_node_development
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: mind_node_test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: mind_node_production
  pool: 5
  timeout: 5000
